"""
Django settings for grocery_shop project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os # Import os module for path joining

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cl#9+r#!3jkjxo(d!xx7y722oorwy+&*5+8ubn*ah*88i$!8fa'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'grocery_shop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Tell Django to look for templates in the project root and app templates folders
        'DIRS': [
            BASE_DIR / 'templates', # For project-wide templates like base.html
        ],
        'APP_DIRS': True, # This will look inside app_name/templates/ (e.g., home/templates/)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'grocery_shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ==================== STATIC FILES (CSS, JavaScript, Images) ====================
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# The URL to use when referring to static files (like in templates)
STATIC_URL = 'static/'

# Additional locations the staticfiles app will traverse to collect static files.
# This tells Django to look for a global 'static' folder in the project root.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# The absolute path to the directory where `collectstatic` will collect static files for deployment.
# Not typically used during development with DEBUG=True, but good to set.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ==================== MEDIA FILES (User Uploads) ====================
# URL that handles the media served from MEDIA_ROOT
MEDIA_URL = '/media/'

# Absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==================== SESSION CONFIGURATION ====================
# Important for your shopping cart which uses sessions
SESSION_ENGINE = 'django.contrib.sessions.backends.db' # Default, stores in database
SESSION_COOKIE_AGE = 1209600 # 2 weeks in seconds (default)
# If you want the cart to expire when the browser closes, uncomment the next line:
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True
LOGIN_URL = '/login/'  # This tells Django where to redirect for login
LOGIN_REDIRECT_URL = '/'  # Where to go after successful login
LOGOUT_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = 'swiftmartswiftmart@gmail.com'
EMAIL_HOST_PASSWORD = 'dfpj kduc xppp dssu'  # Not your real password
DEFAULT_FROM_EMAIL = 'SwiftMart <swiftmartswiftmart@gmail.com>'



AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
