# Generated by Django 5.2.7 on 2026-03-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_orderitem_product_category_orderitem_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='food',
            new_name='item',
        ),
    ]
